using Rapid.Pb;

namespace Rapid;

/// <summary>
/// Interface for cut detection in the Rapid protocol.
/// Cut detectors aggregate failure/join reports and determine when there is
/// sufficient agreement to propose a view change.
/// 
/// A new cut detector is created for each view, so implementations do not need
/// to support clearing state - they are simply replaced on view change.
/// </summary>
internal interface ICutDetector
{
    /// <summary>
    /// Gets the number of proposals that have been generated by this detector.
    /// </summary>
    int GetNumProposals();

    /// <summary>
    /// Apply an AlertMessage against the cut detector. When sufficient reports
    /// have been received about a node (based on the detector's threshold logic),
    /// the method returns a view change proposal.
    /// </summary>
    /// <param name="msg">An AlertMessage to apply against the detector</param>
    /// <returns>A list of endpoints about which a view change has been recorded. Empty list if there is no proposal.</returns>
    List<Endpoint> AggregateForProposal(AlertMessage msg);

    /// <summary>
    /// Invalidates edges between nodes that are failing or have failed. This step may be skipped safely
    /// when there are no failing nodes.
    /// </summary>
    /// <returns>A list of endpoints representing a view change proposal.</returns>
    List<Endpoint> InvalidateFailingEdges();
}
