<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Rapid.Core\Rapid.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.CommandLine" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" />
	</ItemGroup>

</Project>
